[package]
name = "uniswap_v3_sdk"
version = "0.1.0"
authors = ["Zaki Manian <zaki@manian.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
num-rational = "0.4.0"
